//MOCK weather service
const _mock_weather = {
  "location": {
    "name": "Assemini",
    "region": "Sardegna",
    "country": "Italy",
    "lat": 39.29,
    "lon": 9,
    "tz_id": "Europe/Rome",
    "localtime_epoch": 1676925519,
    "localtime": "2023-02-20 21:38"
  },
  "current": {
    "last_updated_epoch": 1676925000,
    "temp_c": 11,
    "is_day": 0,
    "condition": {
      "text": "Mist",
      "icon": "//cdn.weatherapi.com/weather/64x64/night/143.png",
      "code": 1030
    },
    "wind_kph": 6.1,
    "wind_degree": 360,
    "pressure_mb": 1025,
    "precip_mm": 0,
    "humidity": 94,
    "cloud": 0,
    "feelslike_c": 10.6,
    "vis_km": 4.7,
    "uv": 1,
    "gust_kph": 13
  },
  "forecast": {
    "forecastday": [
      {
        "date_epoch": 1676851200,
        "day": {
          "maxtemp_c": 21.7,
          "mintemp_c": 7.7,
          "avgtemp_c": 12.9,
          "maxwind_kph": 15.5,
          "totalprecip_mm": 0,
          "totalsnow_cm": 0,
          "avgvis_km": 10,
          "avghumidity": 64,
          "daily_will_it_rain": 0,
          "daily_chance_of_rain": 0,
          "daily_will_it_snow": 0,
          "daily_chance_of_snow": 0,
          "condition": {
            "text": "Sunny",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
            "code": 1000
          },
          "uv": 4
        },
        "astro": {
          "sunrise": "07:09 AM",
          "sunset": "06:05 PM",
          "moonrise": "07:35 AM",
          "moonset": "06:23 PM",
          "moon_phase": "New Moon",
          "moon_illumination": "0",
          "is_moon_up": 0,
          "is_sun_up": 0
        },
        "hour": [
          {
            "time_epoch": 1676847600,
            "temp_c": 8.1,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_kph": 15.1,
            "wind_degree": 331,
            "pressure_mb": 1026,
            "precip_mm": 0,
            "humidity": 74,
            "cloud": 0,
            "feelslike_c": 5.6,
            "windchill_c": 5.6,
            "heatindex_c": 8.1,
            "dewpoint_c": 3.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 31.7,
            "uv": 1
          },
          {
            "time_epoch": 1676851200,
            "temp_c": 7.9,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_kph": 15.5,
            "wind_degree": 332,
            "pressure_mb": 1026,
            "precip_mm": 0,
            "humidity": 72,
            "cloud": 0,
            "feelslike_c": 5.3,
            "windchill_c": 5.3,
            "heatindex_c": 7.9,
            "dewpoint_c": 3.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 32.4,
            "uv": 1
          },
          {
            "time_epoch": 1676854800,
            "temp_c": 7.7,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_kph": 15.1,
            "wind_degree": 332,
            "pressure_mb": 1026,
            "precip_mm": 0,
            "humidity": 71,
            "cloud": 0,
            "feelslike_c": 5.1,
            "windchill_c": 5.1,
            "heatindex_c": 7.7,
            "dewpoint_c": 2.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 31.7,
            "uv": 1
          },
          {
            "time_epoch": 1676858400,
            "temp_c": 7.7,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_kph": 15.1,
            "wind_degree": 334,
            "pressure_mb": 1025,
            "precip_mm": 0,
            "humidity": 69,
            "cloud": 0,
            "feelslike_c": 5.1,
            "windchill_c": 5.1,
            "heatindex_c": 7.7,
            "dewpoint_c": 2.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 31.7,
            "uv": 1
          },
          {
            "time_epoch": 1676862000,
            "temp_c": 7.8,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_kph": 15.1,
            "wind_degree": 339,
            "pressure_mb": 1025,
            "precip_mm": 0,
            "humidity": 67,
            "cloud": 0,
            "feelslike_c": 5.2,
            "windchill_c": 5.2,
            "heatindex_c": 7.8,
            "dewpoint_c": 2.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 31.7,
            "uv": 1
          },
          {
            "time_epoch": 1676865600,
            "temp_c": 7.8,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_kph": 14.4,
            "wind_degree": 343,
            "pressure_mb": 1025,
            "precip_mm": 0,
            "humidity": 66,
            "cloud": 0,
            "feelslike_c": 5.3,
            "windchill_c": 5.3,
            "heatindex_c": 7.8,
            "dewpoint_c": 1.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 30.2,
            "uv": 1
          },
          {
            "time_epoch": 1676869200,
            "temp_c": 7.8,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_kph": 11.5,
            "wind_degree": 337,
            "pressure_mb": 1026,
            "precip_mm": 0,
            "humidity": 66,
            "cloud": 0,
            "feelslike_c": 5.7,
            "windchill_c": 5.7,
            "heatindex_c": 7.8,
            "dewpoint_c": 1.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 24.1,
            "uv": 1
          },
          {
            "time_epoch": 1676872800,
            "temp_c": 8.8,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_kph": 11.2,
            "wind_degree": 343,
            "pressure_mb": 1026,
            "precip_mm": 0,
            "humidity": 65,
            "cloud": 0,
            "feelslike_c": 7,
            "windchill_c": 7,
            "heatindex_c": 8.8,
            "dewpoint_c": 2.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 23.4,
            "uv": 1
          },
          {
            "time_epoch": 1676876400,
            "temp_c": 10.4,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_kph": 8.6,
            "wind_degree": 348,
            "pressure_mb": 1027,
            "precip_mm": 0,
            "humidity": 62,
            "cloud": 0,
            "feelslike_c": 9.3,
            "windchill_c": 9.3,
            "heatindex_c": 10.4,
            "dewpoint_c": 3.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 17.3,
            "uv": 4
          },
          {
            "time_epoch": 1676880000,
            "temp_c": 12.9,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_kph": 8.3,
            "wind_degree": 317,
            "pressure_mb": 1027,
            "precip_mm": 0,
            "humidity": 56,
            "cloud": 0,
            "feelslike_c": 12.4,
            "windchill_c": 12.4,
            "heatindex_c": 12.9,
            "dewpoint_c": 4.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 11.5,
            "uv": 4
          },
          {
            "time_epoch": 1676883600,
            "temp_c": 15,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_kph": 9,
            "wind_degree": 316,
            "pressure_mb": 1027,
            "precip_mm": 0,
            "humidity": 52,
            "cloud": 0,
            "feelslike_c": 14.7,
            "windchill_c": 14.7,
            "heatindex_c": 15,
            "dewpoint_c": 5.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 10.4,
            "uv": 5
          },
          {
            "time_epoch": 1676887200,
            "temp_c": 18.7,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_kph": 9.4,
            "wind_degree": 307,
            "pressure_mb": 1027,
            "precip_mm": 0,
            "humidity": 50,
            "cloud": 0,
            "feelslike_c": 18.7,
            "windchill_c": 18.7,
            "heatindex_c": 18.7,
            "dewpoint_c": 8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 10.8,
            "uv": 5
          },
          {
            "time_epoch": 1676890800,
            "temp_c": 20.2,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_kph": 10.1,
            "wind_degree": 301,
            "pressure_mb": 1027,
            "precip_mm": 0,
            "humidity": 48,
            "cloud": 0,
            "feelslike_c": 20.2,
            "windchill_c": 20.2,
            "heatindex_c": 20.2,
            "dewpoint_c": 8.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 11.5,
            "uv": 6
          },
          {
            "time_epoch": 1676894400,
            "temp_c": 21.3,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_kph": 11.2,
            "wind_degree": 298,
            "pressure_mb": 1026,
            "precip_mm": 0,
            "humidity": 48,
            "cloud": 0,
            "feelslike_c": 21.3,
            "windchill_c": 21.3,
            "heatindex_c": 24.2,
            "dewpoint_c": 9.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 13,
            "uv": 6
          },
          {
            "time_epoch": 1676898000,
            "temp_c": 21.7,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_kph": 10.4,
            "wind_degree": 289,
            "pressure_mb": 1025,
            "precip_mm": 0,
            "humidity": 48,
            "cloud": 0,
            "feelslike_c": 21.7,
            "windchill_c": 21.7,
            "heatindex_c": 24.3,
            "dewpoint_c": 10.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 11.9,
            "uv": 6
          },
          {
            "time_epoch": 1676901600,
            "temp_c": 21.3,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_kph": 9,
            "wind_degree": 272,
            "pressure_mb": 1025,
            "precip_mm": 0,
            "humidity": 50,
            "cloud": 0,
            "feelslike_c": 21.3,
            "windchill_c": 21.3,
            "heatindex_c": 24.3,
            "dewpoint_c": 10.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 10.4,
            "uv": 6
          },
          {
            "time_epoch": 1676905200,
            "temp_c": 18.4,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_kph": 6.1,
            "wind_degree": 275,
            "pressure_mb": 1025,
            "precip_mm": 0,
            "humidity": 51,
            "cloud": 0,
            "feelslike_c": 18.4,
            "windchill_c": 18.4,
            "heatindex_c": 18.4,
            "dewpoint_c": 8.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 7.2,
            "uv": 5
          },
          {
            "time_epoch": 1676908800,
            "temp_c": 17.5,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_kph": 4.7,
            "wind_degree": 258,
            "pressure_mb": 1024,
            "precip_mm": 0,
            "humidity": 60,
            "cloud": 0,
            "feelslike_c": 17.5,
            "windchill_c": 17.5,
            "heatindex_c": 17.5,
            "dewpoint_c": 9.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 5.4,
            "uv": 5
          },
          {
            "time_epoch": 1676912400,
            "temp_c": 14.4,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_kph": 3.6,
            "wind_degree": 243,
            "pressure_mb": 1025,
            "precip_mm": 0,
            "humidity": 74,
            "cloud": 0,
            "feelslike_c": 15.1,
            "windchill_c": 15.1,
            "heatindex_c": 14.4,
            "dewpoint_c": 9.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 6.1,
            "uv": 4
          },
          {
            "time_epoch": 1676916000,
            "temp_c": 13.1,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_kph": 1.4,
            "wind_degree": 270,
            "pressure_mb": 1025,
            "precip_mm": 0,
            "humidity": 78,
            "cloud": 0,
            "feelslike_c": 13.1,
            "windchill_c": 13.1,
            "heatindex_c": 13.1,
            "dewpoint_c": 9.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 2.9,
            "uv": 1
          },
          {
            "time_epoch": 1676919600,
            "temp_c": 10.4,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_kph": 3.2,
            "wind_degree": 317,
            "pressure_mb": 1025,
            "precip_mm": 0,
            "humidity": 79,
            "cloud": 0,
            "feelslike_c": 10.8,
            "windchill_c": 10.8,
            "heatindex_c": 10.4,
            "dewpoint_c": 6.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 6.8,
            "uv": 1
          },
          {
            "time_epoch": 1676923200,
            "temp_c": 10,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_kph": 6.1,
            "wind_degree": 330,
            "pressure_mb": 1025,
            "precip_mm": 0,
            "humidity": 79,
            "cloud": 0,
            "feelslike_c": 9.4,
            "windchill_c": 9.4,
            "heatindex_c": 10,
            "dewpoint_c": 6.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 13,
            "uv": 1
          },
          {
            "time_epoch": 1676926800,
            "temp_c": 10.2,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_kph": 7.9,
            "wind_degree": 334,
            "pressure_mb": 1025,
            "precip_mm": 0,
            "humidity": 77,
            "cloud": 0,
            "feelslike_c": 9.3,
            "windchill_c": 9.3,
            "heatindex_c": 10.2,
            "dewpoint_c": 6.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 16.6,
            "uv": 1
          },
          {
            "time_epoch": 1676930400,
            "temp_c": 10.3,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_kph": 8.6,
            "wind_degree": 339,
            "pressure_mb": 1025,
            "precip_mm": 0,
            "humidity": 75,
            "cloud": 0,
            "feelslike_c": 9.2,
            "windchill_c": 9.2,
            "heatindex_c": 10.3,
            "dewpoint_c": 6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 18,
            "uv": 1
          }
        ]
      },
      {
        "date_epoch": 1676937600,
        "day": {
          "maxtemp_c": 19.6,
          "mintemp_c": 9.1,
          "avgtemp_c": 12.7,
          "maxwind_kph": 9.4,
          "totalprecip_mm": 0,
          "totalsnow_cm": 0,
          "avgvis_km": 10,
          "avghumidity": 63,
          "daily_will_it_rain": 0,
          "daily_chance_of_rain": 0,
          "daily_will_it_snow": 0,
          "daily_chance_of_snow": 0,
          "condition": {
            "text": "Sunny",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
            "code": 1000
          },
          "uv": 4
        },
        "astro": {
          "sunrise": "07:08 AM",
          "sunset": "06:06 PM",
          "moonrise": "08:05 AM",
          "moonset": "07:40 PM",
          "moon_phase": "Waxing Crescent",
          "moon_illumination": "1",
          "is_moon_up": 0,
          "is_sun_up": 0
        },
        "hour": [
          {
            "time_epoch": 1676934000,
            "temp_c": 10,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_kph": 8.3,
            "wind_degree": 334,
            "pressure_mb": 1025,
            "precip_mm": 0,
            "humidity": 73,
            "cloud": 0,
            "feelslike_c": 8.9,
            "windchill_c": 8.9,
            "heatindex_c": 10,
            "dewpoint_c": 5.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 17.3,
            "uv": 1
          },
          {
            "time_epoch": 1676937600,
            "temp_c": 9.8,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_kph": 8.6,
            "wind_degree": 327,
            "pressure_mb": 1025,
            "precip_mm": 0,
            "humidity": 72,
            "cloud": 0,
            "feelslike_c": 8.6,
            "windchill_c": 8.6,
            "heatindex_c": 9.8,
            "dewpoint_c": 5.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 18,
            "uv": 1
          },
          {
            "time_epoch": 1676941200,
            "temp_c": 9.5,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_kph": 8.6,
            "wind_degree": 333,
            "pressure_mb": 1024,
            "precip_mm": 0,
            "humidity": 72,
            "cloud": 3,
            "feelslike_c": 8.3,
            "windchill_c": 8.3,
            "heatindex_c": 9.5,
            "dewpoint_c": 4.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 18,
            "uv": 1
          },
          {
            "time_epoch": 1676944800,
            "temp_c": 9.6,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_kph": 8.3,
            "wind_degree": 331,
            "pressure_mb": 1024,
            "precip_mm": 0,
            "humidity": 72,
            "cloud": 1,
            "feelslike_c": 8.5,
            "windchill_c": 8.5,
            "heatindex_c": 9.6,
            "dewpoint_c": 4.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 17.3,
            "uv": 1
          },
          {
            "time_epoch": 1676948400,
            "temp_c": 9.5,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_kph": 8.6,
            "wind_degree": 325,
            "pressure_mb": 1023,
            "precip_mm": 0,
            "humidity": 71,
            "cloud": 1,
            "feelslike_c": 8.3,
            "windchill_c": 8.3,
            "heatindex_c": 9.5,
            "dewpoint_c": 4.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 18,
            "uv": 1
          },
          {
            "time_epoch": 1676952000,
            "temp_c": 9.3,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_kph": 8.3,
            "wind_degree": 330,
            "pressure_mb": 1023,
            "precip_mm": 0,
            "humidity": 70,
            "cloud": 0,
            "feelslike_c": 8.1,
            "windchill_c": 8.1,
            "heatindex_c": 9.3,
            "dewpoint_c": 4.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 17.3,
            "uv": 1
          },
          {
            "time_epoch": 1676955600,
            "temp_c": 9.2,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_kph": 8.6,
            "wind_degree": 323,
            "pressure_mb": 1023,
            "precip_mm": 0,
            "humidity": 69,
            "cloud": 0,
            "feelslike_c": 7.9,
            "windchill_c": 7.9,
            "heatindex_c": 9.2,
            "dewpoint_c": 3.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 18,
            "uv": 1
          },
          {
            "time_epoch": 1676959200,
            "temp_c": 9.1,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_kph": 9.4,
            "wind_degree": 325,
            "pressure_mb": 1023,
            "precip_mm": 0,
            "humidity": 68,
            "cloud": 0,
            "feelslike_c": 7.7,
            "windchill_c": 7.7,
            "heatindex_c": 9.1,
            "dewpoint_c": 3.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 19.8,
            "uv": 1
          },
          {
            "time_epoch": 1676962800,
            "temp_c": 10.7,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_kph": 9,
            "wind_degree": 323,
            "pressure_mb": 1023,
            "precip_mm": 0,
            "humidity": 63,
            "cloud": 0,
            "feelslike_c": 9.6,
            "windchill_c": 9.6,
            "heatindex_c": 10.7,
            "dewpoint_c": 3.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 18.7,
            "uv": 4
          },
          {
            "time_epoch": 1676966400,
            "temp_c": 13.4,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_kph": 9,
            "wind_degree": 314,
            "pressure_mb": 1023,
            "precip_mm": 0,
            "humidity": 55,
            "cloud": 0,
            "feelslike_c": 12.8,
            "windchill_c": 12.8,
            "heatindex_c": 13.4,
            "dewpoint_c": 4.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 13,
            "uv": 4
          },
          {
            "time_epoch": 1676970000,
            "temp_c": 15.4,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_kph": 8.3,
            "wind_degree": 304,
            "pressure_mb": 1023,
            "precip_mm": 0,
            "humidity": 49,
            "cloud": 1,
            "feelslike_c": 15.4,
            "windchill_c": 15.4,
            "heatindex_c": 15.4,
            "dewpoint_c": 4.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 9.7,
            "uv": 5
          },
          {
            "time_epoch": 1676973600,
            "temp_c": 17.6,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_kph": 8.3,
            "wind_degree": 297,
            "pressure_mb": 1022,
            "precip_mm": 0,
            "humidity": 46,
            "cloud": 7,
            "feelslike_c": 17.6,
            "windchill_c": 17.6,
            "heatindex_c": 17.6,
            "dewpoint_c": 5.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 9.4,
            "uv": 5
          },
          {
            "time_epoch": 1676977200,
            "temp_c": 18.8,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_kph": 7.9,
            "wind_degree": 288,
            "pressure_mb": 1022,
            "precip_mm": 0,
            "humidity": 43,
            "cloud": 7,
            "feelslike_c": 18.8,
            "windchill_c": 18.8,
            "heatindex_c": 18.8,
            "dewpoint_c": 6.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 9,
            "uv": 5
          },
          {
            "time_epoch": 1676980800,
            "temp_c": 19.6,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_kph": 7.6,
            "wind_degree": 276,
            "pressure_mb": 1021,
            "precip_mm": 0,
            "humidity": 41,
            "cloud": 7,
            "feelslike_c": 19.6,
            "windchill_c": 19.6,
            "heatindex_c": 19.6,
            "dewpoint_c": 5.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 8.6,
            "uv": 5
          },
          {
            "time_epoch": 1676984400,
            "temp_c": 19.6,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_kph": 7.6,
            "wind_degree": 261,
            "pressure_mb": 1020,
            "precip_mm": 0,
            "humidity": 41,
            "cloud": 10,
            "feelslike_c": 19.6,
            "windchill_c": 19.6,
            "heatindex_c": 19.6,
            "dewpoint_c": 6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 8.6,
            "uv": 5
          },
          {
            "time_epoch": 1676988000,
            "temp_c": 19.5,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_kph": 8.3,
            "wind_degree": 245,
            "pressure_mb": 1020,
            "precip_mm": 0,
            "humidity": 43,
            "cloud": 10,
            "feelslike_c": 19.5,
            "windchill_c": 19.5,
            "heatindex_c": 19.5,
            "dewpoint_c": 6.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 9.4,
            "uv": 5
          },
          {
            "time_epoch": 1676991600,
            "temp_c": 18.7,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_kph": 7.9,
            "wind_degree": 224,
            "pressure_mb": 1019,
            "precip_mm": 0,
            "humidity": 49,
            "cloud": 11,
            "feelslike_c": 18.7,
            "windchill_c": 18.7,
            "heatindex_c": 18.7,
            "dewpoint_c": 7.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 9,
            "uv": 5
          },
          {
            "time_epoch": 1676995200,
            "temp_c": 15.6,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_kph": 6.8,
            "wind_degree": 201,
            "pressure_mb": 1019,
            "precip_mm": 0,
            "humidity": 60,
            "cloud": 18,
            "feelslike_c": 15.6,
            "windchill_c": 15.6,
            "heatindex_c": 15.6,
            "dewpoint_c": 7.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 10.8,
            "uv": 5
          },
          {
            "time_epoch": 1676998800,
            "temp_c": 11.8,
            "is_day": 1,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_kph": 6.1,
            "wind_degree": 156,
            "pressure_mb": 1019,
            "precip_mm": 0,
            "humidity": 73,
            "cloud": 33,
            "feelslike_c": 11.5,
            "windchill_c": 11.5,
            "heatindex_c": 11.8,
            "dewpoint_c": 7.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 13,
            "uv": 4
          },
          {
            "time_epoch": 1677002400,
            "temp_c": 10.9,
            "is_day": 0,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_kph": 5,
            "wind_degree": 123,
            "pressure_mb": 1020,
            "precip_mm": 0,
            "humidity": 76,
            "cloud": 28,
            "feelslike_c": 10.8,
            "windchill_c": 10.8,
            "heatindex_c": 10.9,
            "dewpoint_c": 6.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 10.4,
            "uv": 1
          },
          {
            "time_epoch": 1677006000,
            "temp_c": 10.2,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_kph": 4,
            "wind_degree": 111,
            "pressure_mb": 1020,
            "precip_mm": 0,
            "humidity": 76,
            "cloud": 15,
            "feelslike_c": 10.3,
            "windchill_c": 10.3,
            "heatindex_c": 10.2,
            "dewpoint_c": 6.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 8.3,
            "uv": 1
          },
          {
            "time_epoch": 1677009600,
            "temp_c": 9.7,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_kph": 2.5,
            "wind_degree": 100,
            "pressure_mb": 1020,
            "precip_mm": 0,
            "humidity": 77,
            "cloud": 9,
            "feelslike_c": 9.7,
            "windchill_c": 9.7,
            "heatindex_c": 9.7,
            "dewpoint_c": 5.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 5.4,
            "uv": 1
          },
          {
            "time_epoch": 1677013200,
            "temp_c": 9.3,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_kph": 2.9,
            "wind_degree": 58,
            "pressure_mb": 1020,
            "precip_mm": 0,
            "humidity": 78,
            "cloud": 14,
            "feelslike_c": 9.3,
            "windchill_c": 9.3,
            "heatindex_c": 9.3,
            "dewpoint_c": 5.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 6.1,
            "uv": 1
          },
          {
            "time_epoch": 1677016800,
            "temp_c": 9.1,
            "is_day": 0,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_kph": 3.6,
            "wind_degree": 42,
            "pressure_mb": 1020,
            "precip_mm": 0,
            "humidity": 77,
            "cloud": 32,
            "feelslike_c": 9.2,
            "windchill_c": 9.2,
            "heatindex_c": 9.1,
            "dewpoint_c": 5.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 7.6,
            "uv": 1
          }
        ]
      },
      {
        "date_epoch": 1677024000,
        "day": {
          "maxtemp_c": 17.6,
          "mintemp_c": 8.1,
          "avgtemp_c": 12,
          "maxwind_kph": 8.6,
          "totalprecip_mm": 0,
          "totalsnow_cm": 0,
          "avgvis_km": 10,
          "avghumidity": 68,
          "daily_will_it_rain": 0,
          "daily_chance_of_rain": 0,
          "daily_will_it_snow": 0,
          "daily_chance_of_snow": 0,
          "condition": {
            "text": "Sunny",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
            "code": 1000
          },
          "uv": 4
        },
        "astro": {
          "sunrise": "07:06 AM",
          "sunset": "06:07 PM",
          "moonrise": "08:32 AM",
          "moonset": "08:53 PM",
          "moon_phase": "Waxing Crescent",
          "moon_illumination": "4",
          "is_moon_up": 0,
          "is_sun_up": 0
        },
        "hour": [
          {
            "time_epoch": 1677020400,
            "temp_c": 8.8,
            "is_day": 0,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_kph": 3.2,
            "wind_degree": 56,
            "pressure_mb": 1020,
            "precip_mm": 0,
            "humidity": 76,
            "cloud": 33,
            "feelslike_c": 9.1,
            "windchill_c": 9.1,
            "heatindex_c": 8.8,
            "dewpoint_c": 4.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 6.8,
            "uv": 1
          },
          {
            "time_epoch": 1677024000,
            "temp_c": 8.7,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_kph": 2.5,
            "wind_degree": 38,
            "pressure_mb": 1019,
            "precip_mm": 0,
            "humidity": 76,
            "cloud": 14,
            "feelslike_c": 8.7,
            "windchill_c": 8.7,
            "heatindex_c": 8.7,
            "dewpoint_c": 4.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 5.4,
            "uv": 1
          },
          {
            "time_epoch": 1677027600,
            "temp_c": 8.5,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_kph": 2.5,
            "wind_degree": 4,
            "pressure_mb": 1019,
            "precip_mm": 0,
            "humidity": 75,
            "cloud": 12,
            "feelslike_c": 8.5,
            "windchill_c": 8.5,
            "heatindex_c": 8.5,
            "dewpoint_c": 4.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 5.4,
            "uv": 1
          },
          {
            "time_epoch": 1677031200,
            "temp_c": 8.3,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_kph": 4,
            "wind_degree": 337,
            "pressure_mb": 1019,
            "precip_mm": 0,
            "humidity": 75,
            "cloud": 21,
            "feelslike_c": 8.2,
            "windchill_c": 8.2,
            "heatindex_c": 8.3,
            "dewpoint_c": 4.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 8.3,
            "uv": 1
          },
          {
            "time_epoch": 1677034800,
            "temp_c": 8.1,
            "is_day": 0,
            "condition": {
              "text": "Cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
              "code": 1006
            },
            "wind_kph": 4.7,
            "wind_degree": 358,
            "pressure_mb": 1018,
            "precip_mm": 0,
            "humidity": 75,
            "cloud": 65,
            "feelslike_c": 7.7,
            "windchill_c": 7.7,
            "heatindex_c": 8.1,
            "dewpoint_c": 3.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 9.7,
            "uv": 1
          },
          {
            "time_epoch": 1677038400,
            "temp_c": 8.3,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_kph": 4,
            "wind_degree": 4,
            "pressure_mb": 1018,
            "precip_mm": 0,
            "humidity": 72,
            "cloud": 9,
            "feelslike_c": 8.2,
            "windchill_c": 8.2,
            "heatindex_c": 8.3,
            "dewpoint_c": 3.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 8.3,
            "uv": 1
          },
          {
            "time_epoch": 1677042000,
            "temp_c": 8.7,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_kph": 2.5,
            "wind_degree": 15,
            "pressure_mb": 1018,
            "precip_mm": 0,
            "humidity": 70,
            "cloud": 17,
            "feelslike_c": 8.7,
            "windchill_c": 8.7,
            "heatindex_c": 8.7,
            "dewpoint_c": 3.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 5.4,
            "uv": 1
          },
          {
            "time_epoch": 1677045600,
            "temp_c": 9.2,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_kph": 2.2,
            "wind_degree": 43,
            "pressure_mb": 1018,
            "precip_mm": 0,
            "humidity": 69,
            "cloud": 22,
            "feelslike_c": 9.2,
            "windchill_c": 9.2,
            "heatindex_c": 9.2,
            "dewpoint_c": 3.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 4.7,
            "uv": 1
          },
          {
            "time_epoch": 1677049200,
            "temp_c": 10.9,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_kph": 2.2,
            "wind_degree": 68,
            "pressure_mb": 1018,
            "precip_mm": 0,
            "humidity": 66,
            "cloud": 22,
            "feelslike_c": 10.9,
            "windchill_c": 10.9,
            "heatindex_c": 10.9,
            "dewpoint_c": 4.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 4.3,
            "uv": 4
          },
          {
            "time_epoch": 1677052800,
            "temp_c": 13.4,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_kph": 0.7,
            "wind_degree": 148,
            "pressure_mb": 1019,
            "precip_mm": 0,
            "humidity": 56,
            "cloud": 23,
            "feelslike_c": 13.4,
            "windchill_c": 13.4,
            "heatindex_c": 13.4,
            "dewpoint_c": 4.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 1.1,
            "uv": 4
          },
          {
            "time_epoch": 1677056400,
            "temp_c": 14.8,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_kph": 3.2,
            "wind_degree": 200,
            "pressure_mb": 1019,
            "precip_mm": 0,
            "humidity": 53,
            "cloud": 19,
            "feelslike_c": 15.7,
            "windchill_c": 15.7,
            "heatindex_c": 14.8,
            "dewpoint_c": 5.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 3.6,
            "uv": 4
          },
          {
            "time_epoch": 1677060000,
            "temp_c": 16,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_kph": 4.7,
            "wind_degree": 217,
            "pressure_mb": 1019,
            "precip_mm": 0,
            "humidity": 52,
            "cloud": 7,
            "feelslike_c": 16,
            "windchill_c": 16,
            "heatindex_c": 16,
            "dewpoint_c": 6.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 5.4,
            "uv": 5
          },
          {
            "time_epoch": 1677063600,
            "temp_c": 16.7,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_kph": 5,
            "wind_degree": 203,
            "pressure_mb": 1018,
            "precip_mm": 0,
            "humidity": 51,
            "cloud": 7,
            "feelslike_c": 16.7,
            "windchill_c": 16.7,
            "heatindex_c": 16.7,
            "dewpoint_c": 6.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 5.8,
            "uv": 5
          },
          {
            "time_epoch": 1677067200,
            "temp_c": 16.8,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_kph": 7.2,
            "wind_degree": 188,
            "pressure_mb": 1017,
            "precip_mm": 0,
            "humidity": 51,
            "cloud": 10,
            "feelslike_c": 16.8,
            "windchill_c": 16.8,
            "heatindex_c": 16.8,
            "dewpoint_c": 6.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 8.3,
            "uv": 5
          },
          {
            "time_epoch": 1677070800,
            "temp_c": 17.6,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_kph": 8.3,
            "wind_degree": 182,
            "pressure_mb": 1017,
            "precip_mm": 0,
            "humidity": 52,
            "cloud": 15,
            "feelslike_c": 17.6,
            "windchill_c": 17.6,
            "heatindex_c": 17.6,
            "dewpoint_c": 7.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 9.4,
            "uv": 5
          },
          {
            "time_epoch": 1677074400,
            "temp_c": 17.4,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_kph": 8.6,
            "wind_degree": 184,
            "pressure_mb": 1016,
            "precip_mm": 0,
            "humidity": 54,
            "cloud": 17,
            "feelslike_c": 17.4,
            "windchill_c": 17.4,
            "heatindex_c": 17.4,
            "dewpoint_c": 8.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 10.1,
            "uv": 5
          },
          {
            "time_epoch": 1677078000,
            "temp_c": 17.4,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_kph": 8.3,
            "wind_degree": 185,
            "pressure_mb": 1016,
            "precip_mm": 0,
            "humidity": 58,
            "cloud": 7,
            "feelslike_c": 17.4,
            "windchill_c": 17.4,
            "heatindex_c": 17.4,
            "dewpoint_c": 9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 9.4,
            "uv": 5
          },
          {
            "time_epoch": 1677081600,
            "temp_c": 14.5,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_kph": 6.8,
            "wind_degree": 175,
            "pressure_mb": 1016,
            "precip_mm": 0,
            "humidity": 64,
            "cloud": 24,
            "feelslike_c": 14.5,
            "windchill_c": 14.5,
            "heatindex_c": 14.5,
            "dewpoint_c": 7.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 10.1,
            "uv": 4
          },
          {
            "time_epoch": 1677085200,
            "temp_c": 11.7,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_kph": 4.7,
            "wind_degree": 155,
            "pressure_mb": 1016,
            "precip_mm": 0,
            "humidity": 78,
            "cloud": 11,
            "feelslike_c": 11.8,
            "windchill_c": 11.8,
            "heatindex_c": 11.7,
            "dewpoint_c": 8.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 9.7,
            "uv": 4
          },
          {
            "time_epoch": 1677088800,
            "temp_c": 11.3,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_kph": 3.6,
            "wind_degree": 126,
            "pressure_mb": 1017,
            "precip_mm": 0,
            "humidity": 79,
            "cloud": 17,
            "feelslike_c": 11.7,
            "windchill_c": 11.7,
            "heatindex_c": 11.3,
            "dewpoint_c": 7.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 7.6,
            "uv": 1
          },
          {
            "time_epoch": 1677092400,
            "temp_c": 10.7,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_kph": 2.2,
            "wind_degree": 152,
            "pressure_mb": 1017,
            "precip_mm": 0,
            "humidity": 80,
            "cloud": 19,
            "feelslike_c": 10.7,
            "windchill_c": 10.7,
            "heatindex_c": 10.7,
            "dewpoint_c": 7.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 4.7,
            "uv": 1
          },
          {
            "time_epoch": 1677096000,
            "temp_c": 10.2,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_kph": 1.4,
            "wind_degree": 99,
            "pressure_mb": 1017,
            "precip_mm": 0,
            "humidity": 80,
            "cloud": 23,
            "feelslike_c": 10.2,
            "windchill_c": 10.2,
            "heatindex_c": 10.2,
            "dewpoint_c": 6.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 2.9,
            "uv": 1
          },
          {
            "time_epoch": 1677099600,
            "temp_c": 10.1,
            "is_day": 0,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_kph": 1.1,
            "wind_degree": 62,
            "pressure_mb": 1017,
            "precip_mm": 0,
            "humidity": 79,
            "cloud": 50,
            "feelslike_c": 10.1,
            "windchill_c": 10.1,
            "heatindex_c": 10.1,
            "dewpoint_c": 6.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 2.2,
            "uv": 1
          },
          {
            "time_epoch": 1677103200,
            "temp_c": 10.4,
            "is_day": 0,
            "condition": {
              "text": "Overcast",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
              "code": 1009
            },
            "wind_kph": 2.2,
            "wind_degree": 129,
            "pressure_mb": 1017,
            "precip_mm": 0,
            "humidity": 79,
            "cloud": 95,
            "feelslike_c": 10.4,
            "windchill_c": 10.4,
            "heatindex_c": 10.4,
            "dewpoint_c": 6.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 4.7,
            "uv": 1
          }
        ]
      },
      {
        "date_epoch": 1677110400,
        "day": {
          "maxtemp_c": 18.7,
          "mintemp_c": 8.6,
          "avgtemp_c": 13,
          "maxwind_kph": 11.5,
          "totalprecip_mm": 0,
          "totalsnow_cm": 0,
          "avgvis_km": 10,
          "avghumidity": 74,
          "daily_will_it_rain": 0,
          "daily_chance_of_rain": 0,
          "daily_will_it_snow": 0,
          "daily_chance_of_snow": 0,
          "condition": {
            "text": "Sunny",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
            "code": 1000
          },
          "uv": 4
        },
        "astro": {
          "sunrise": "07:05 AM",
          "sunset": "06:09 PM",
          "moonrise": "08:58 AM",
          "moonset": "10:04 PM",
          "moon_phase": "Waxing Crescent",
          "moon_illumination": "10",
          "is_moon_up": 0,
          "is_sun_up": 0
        },
        "hour": [
          {
            "time_epoch": 1677106800,
            "temp_c": 10.2,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_kph": 4,
            "wind_degree": 117,
            "pressure_mb": 1017,
            "precip_mm": 0,
            "humidity": 78,
            "cloud": 19,
            "feelslike_c": 10.3,
            "windchill_c": 10.3,
            "heatindex_c": 10.2,
            "dewpoint_c": 6.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 8.3,
            "uv": 1
          },
          {
            "time_epoch": 1677110400,
            "temp_c": 9.7,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_kph": 2.9,
            "wind_degree": 125,
            "pressure_mb": 1016,
            "precip_mm": 0,
            "humidity": 79,
            "cloud": 15,
            "feelslike_c": 9.7,
            "windchill_c": 9.7,
            "heatindex_c": 9.7,
            "dewpoint_c": 6.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 6.1,
            "uv": 1
          },
          {
            "time_epoch": 1677114000,
            "temp_c": 9.3,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_kph": 2.2,
            "wind_degree": 109,
            "pressure_mb": 1016,
            "precip_mm": 0,
            "humidity": 80,
            "cloud": 22,
            "feelslike_c": 9.3,
            "windchill_c": 9.3,
            "heatindex_c": 9.3,
            "dewpoint_c": 6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 4.7,
            "uv": 1
          },
          {
            "time_epoch": 1677117600,
            "temp_c": 9.1,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_kph": 2.9,
            "wind_degree": 35,
            "pressure_mb": 1015,
            "precip_mm": 0,
            "humidity": 79,
            "cloud": 18,
            "feelslike_c": 9.1,
            "windchill_c": 9.1,
            "heatindex_c": 9.1,
            "dewpoint_c": 5.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 6.1,
            "uv": 1
          },
          {
            "time_epoch": 1677121200,
            "temp_c": 8.9,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_kph": 3.2,
            "wind_degree": 22,
            "pressure_mb": 1015,
            "precip_mm": 0,
            "humidity": 78,
            "cloud": 5,
            "feelslike_c": 9.2,
            "windchill_c": 9.2,
            "heatindex_c": 8.9,
            "dewpoint_c": 5.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 6.8,
            "uv": 1
          },
          {
            "time_epoch": 1677124800,
            "temp_c": 8.6,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_kph": 3.2,
            "wind_degree": 354,
            "pressure_mb": 1015,
            "precip_mm": 0,
            "humidity": 77,
            "cloud": 4,
            "feelslike_c": 8.9,
            "windchill_c": 8.9,
            "heatindex_c": 8.6,
            "dewpoint_c": 4.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 6.8,
            "uv": 1
          },
          {
            "time_epoch": 1677128400,
            "temp_c": 8.8,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_kph": 2.5,
            "wind_degree": 356,
            "pressure_mb": 1015,
            "precip_mm": 0,
            "humidity": 76,
            "cloud": 4,
            "feelslike_c": 8.8,
            "windchill_c": 8.8,
            "heatindex_c": 8.8,
            "dewpoint_c": 4.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 5.4,
            "uv": 1
          },
          {
            "time_epoch": 1677132000,
            "temp_c": 9,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_kph": 1.4,
            "wind_degree": 8,
            "pressure_mb": 1015,
            "precip_mm": 0,
            "humidity": 76,
            "cloud": 3,
            "feelslike_c": 9,
            "windchill_c": 9,
            "heatindex_c": 9,
            "dewpoint_c": 5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 2.9,
            "uv": 1
          },
          {
            "time_epoch": 1677135600,
            "temp_c": 11,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_kph": 2.2,
            "wind_degree": 33,
            "pressure_mb": 1015,
            "precip_mm": 0,
            "humidity": 73,
            "cloud": 3,
            "feelslike_c": 11,
            "windchill_c": 11,
            "heatindex_c": 11,
            "dewpoint_c": 6.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 4,
            "uv": 4
          },
          {
            "time_epoch": 1677139200,
            "temp_c": 13.4,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_kph": 0.7,
            "wind_degree": 82,
            "pressure_mb": 1015,
            "precip_mm": 0,
            "humidity": 63,
            "cloud": 3,
            "feelslike_c": 13.4,
            "windchill_c": 13.4,
            "heatindex_c": 13.4,
            "dewpoint_c": 6.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 0.7,
            "uv": 4
          },
          {
            "time_epoch": 1677142800,
            "temp_c": 14.9,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_kph": 2.5,
            "wind_degree": 182,
            "pressure_mb": 1015,
            "precip_mm": 0,
            "humidity": 60,
            "cloud": 3,
            "feelslike_c": 14.9,
            "windchill_c": 14.9,
            "heatindex_c": 14.9,
            "dewpoint_c": 7.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 2.9,
            "uv": 4
          },
          {
            "time_epoch": 1677146400,
            "temp_c": 16.1,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_kph": 5.8,
            "wind_degree": 183,
            "pressure_mb": 1015,
            "precip_mm": 0,
            "humidity": 58,
            "cloud": 3,
            "feelslike_c": 16.1,
            "windchill_c": 16.1,
            "heatindex_c": 16.1,
            "dewpoint_c": 7.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 6.5,
            "uv": 5
          },
          {
            "time_epoch": 1677150000,
            "temp_c": 17.9,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_kph": 8.3,
            "wind_degree": 180,
            "pressure_mb": 1015,
            "precip_mm": 0,
            "humidity": 58,
            "cloud": 3,
            "feelslike_c": 17.9,
            "windchill_c": 17.9,
            "heatindex_c": 17.9,
            "dewpoint_c": 9.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 9.4,
            "uv": 5
          },
          {
            "time_epoch": 1677153600,
            "temp_c": 18.6,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_kph": 9.4,
            "wind_degree": 175,
            "pressure_mb": 1014,
            "precip_mm": 0,
            "humidity": 60,
            "cloud": 2,
            "feelslike_c": 18.6,
            "windchill_c": 18.6,
            "heatindex_c": 18.6,
            "dewpoint_c": 10.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 10.8,
            "uv": 5
          },
          {
            "time_epoch": 1677157200,
            "temp_c": 18.7,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_kph": 10.1,
            "wind_degree": 174,
            "pressure_mb": 1014,
            "precip_mm": 0,
            "humidity": 62,
            "cloud": 3,
            "feelslike_c": 18.7,
            "windchill_c": 18.7,
            "heatindex_c": 18.7,
            "dewpoint_c": 11.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 11.5,
            "uv": 5
          },
          {
            "time_epoch": 1677160800,
            "temp_c": 18.6,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_kph": 11.5,
            "wind_degree": 172,
            "pressure_mb": 1014,
            "precip_mm": 0,
            "humidity": 66,
            "cloud": 3,
            "feelslike_c": 18.6,
            "windchill_c": 18.6,
            "heatindex_c": 18.6,
            "dewpoint_c": 12.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 13.3,
            "uv": 5
          },
          {
            "time_epoch": 1677164400,
            "temp_c": 18.1,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_kph": 11.5,
            "wind_degree": 164,
            "pressure_mb": 1013,
            "precip_mm": 0,
            "humidity": 70,
            "cloud": 4,
            "feelslike_c": 18.1,
            "windchill_c": 18.1,
            "heatindex_c": 18.1,
            "dewpoint_c": 12.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 13.3,
            "uv": 5
          },
          {
            "time_epoch": 1677168000,
            "temp_c": 16.9,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_kph": 10.1,
            "wind_degree": 156,
            "pressure_mb": 1014,
            "precip_mm": 0,
            "humidity": 75,
            "cloud": 5,
            "feelslike_c": 16.9,
            "windchill_c": 16.9,
            "heatindex_c": 16.9,
            "dewpoint_c": 12.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 11.5,
            "uv": 5
          },
          {
            "time_epoch": 1677171600,
            "temp_c": 14.6,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_kph": 9,
            "wind_degree": 140,
            "pressure_mb": 1014,
            "precip_mm": 0,
            "humidity": 87,
            "cloud": 4,
            "feelslike_c": 14.3,
            "windchill_c": 14.3,
            "heatindex_c": 14.6,
            "dewpoint_c": 12.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 13,
            "uv": 4
          },
          {
            "time_epoch": 1677175200,
            "temp_c": 14.6,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_kph": 8.3,
            "wind_degree": 117,
            "pressure_mb": 1014,
            "precip_mm": 0,
            "humidity": 87,
            "cloud": 3,
            "feelslike_c": 14.4,
            "windchill_c": 14.4,
            "heatindex_c": 14.6,
            "dewpoint_c": 12.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 11.5,
            "uv": 1
          },
          {
            "time_epoch": 1677178800,
            "temp_c": 11.9,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_kph": 7.9,
            "wind_degree": 114,
            "pressure_mb": 1015,
            "precip_mm": 0,
            "humidity": 86,
            "cloud": 3,
            "feelslike_c": 11.2,
            "windchill_c": 11.2,
            "heatindex_c": 11.9,
            "dewpoint_c": 9.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 16.6,
            "uv": 1
          },
          {
            "time_epoch": 1677182400,
            "temp_c": 11.4,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_kph": 8.3,
            "wind_degree": 111,
            "pressure_mb": 1015,
            "precip_mm": 0,
            "humidity": 85,
            "cloud": 5,
            "feelslike_c": 10.6,
            "windchill_c": 10.6,
            "heatindex_c": 11.4,
            "dewpoint_c": 9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 17.3,
            "uv": 1
          },
          {
            "time_epoch": 1677186000,
            "temp_c": 11.4,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_kph": 8.6,
            "wind_degree": 108,
            "pressure_mb": 1015,
            "precip_mm": 0,
            "humidity": 84,
            "cloud": 5,
            "feelslike_c": 10.5,
            "windchill_c": 10.5,
            "heatindex_c": 11.4,
            "dewpoint_c": 8.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 18,
            "uv": 1
          },
          {
            "time_epoch": 1677189600,
            "temp_c": 11.1,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_kph": 9,
            "wind_degree": 101,
            "pressure_mb": 1015,
            "precip_mm": 0,
            "humidity": 83,
            "cloud": 4,
            "feelslike_c": 10.1,
            "windchill_c": 10.1,
            "heatindex_c": 11.1,
            "dewpoint_c": 8.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "gust_kph": 18.7,
            "uv": 1
          }
        ]
      }
    ]
  }
};